// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzcelvlhvyxirynrmsry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6Y2Vsdmxodnl4aXJ5bnJtc3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTU0MjIsImV4cCI6MjA1OTI3MTQyMn0.U9g70mgq4q8_-XtLmFzB-RcQ7upo52nJzRDftLNFdig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);